apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: application1
  name: application1
  namespace: java-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: application1
    spec:
      containers:
      - image: dkasha14/application1
        name: application1
        resources: {}
status: {}
